version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: ecoride-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ecoride-net

volumes:
  mongo-data:

networks:
  ecoride-net:
