spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecoride_qa
    username: postgres
    password: qapass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: votre.email@gmail.com
    password: votreMotDePasseApp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8083

ecoride:
  env: qa
