spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecoride_qa
    username: postgres
    password: qapass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8083

ecoride:
  env: qa
