spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecoride_dev
    username: postgres
    password: devpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8083

ecoride:
  env: dev
